# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis_3/pwm_3.srcs/sources_1/bd/sist/ip/sist_auto_pc_0/sist_auto_pc_0.xci
# IP: The module: 'sist_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis_3/pwm_3.srcs/sources_1/bd/sist/ip/sist_auto_pc_0/sist_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sist_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis_3/pwm_3.srcs/sources_1/bd/sist/ip/sist_auto_pc_0/sist_auto_pc_0.xci
# IP: The module: 'sist_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis_3/pwm_3.srcs/sources_1/bd/sist/ip/sist_auto_pc_0/sist_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sist_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
