# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sist/sist.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sist || ORIG_REF_NAME==sist} -quiet] -quiet

# IP: bd/sist/ip/sist_processing_system7_0_0/sist_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sist_processing_system7_0_0 || ORIG_REF_NAME==sist_processing_system7_0_0} -quiet] -quiet

# IP: bd/sist/ip/sist_pwm_3ip_0_0/sist_pwm_3ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sist_pwm_3ip_0_0 || ORIG_REF_NAME==sist_pwm_3ip_0_0} -quiet] -quiet

# IP: bd/sist/ip/sist_ps7_0_axi_periph_0/sist_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sist_ps7_0_axi_periph_0 || ORIG_REF_NAME==sist_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sist/ip/sist_rst_ps7_0_100M_0/sist_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sist_rst_ps7_0_100M_0 || ORIG_REF_NAME==sist_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sist/ip/sist_ila_0_0/sist_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sist_ila_0_0 || ORIG_REF_NAME==sist_ila_0_0} -quiet] -quiet

# IP: bd/sist/ip/sist_auto_pc_0/sist_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sist_auto_pc_0 || ORIG_REF_NAME==sist_auto_pc_0} -quiet] -quiet

# XDC: bd/sist/sist_ooc.xdc
