# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis/project_pwm.srcs/sources_1/bd/sistema/ip/sistema_ila_0_0/sistema_ila_0_0.xci
# IP: The module: 'sistema_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis/project_pwm.srcs/sources_1/bd/sistema/ip/sistema_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis/project_pwm.srcs/sources_1/bd/sistema/ip/sistema_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis/project_pwm.srcs/sources_1/bd/sistema/ip/sistema_ila_0_0/sistema_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis/project_pwm.srcs/sources_1/bd/sistema/ip/sistema_ila_0_0/sistema_ila_0_0.xci
# IP: The module: 'sistema_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis/project_pwm.srcs/sources_1/bd/sistema/ip/sistema_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis/project_pwm.srcs/sources_1/bd/sistema/ip/sistema_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CESE_UBA/Mysoft/Pro_final_pwm/Sintesis/project_pwm.srcs/sources_1/bd/sistema/ip/sistema_ila_0_0/sistema_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
